/* 订单自动核对：截图仅保存在当前设备，不会写进导出的 products.js。 */
const orderForm=document.querySelector('#orderCheckForm'),orderProduct=document.querySelector('#orderProduct'),expectedProduct=document.querySelector('#expectedProduct'),checksEl=document.querySelector('#autoChecks'),successEl=document.querySelector('#orderSuccess'),recordsEl=document.querySelector('#orderRecords');
const checkCustomer=document.querySelector('#checkCustomer'),checkFields={brand:document.querySelector('#checkBrand'),style:document.querySelector('#checkStyle'),color:document.querySelector('#checkColor'),size:document.querySelector('#checkSize'),amount:document.querySelector('#checkAmount')};
const receiptState={customer:'',owner:''};
function allOrderProducts(){const base=Array.isArray(window.PRODUCTS)?window.PRODUCTS:[],local=load(PRODUCT_KEY);return [...base.filter(p=>!local.some(x=>x.id===p.id)),...local]}
function currentOrderProduct(){return allOrderProducts().find(p=>String(p.id)===orderProduct.value)}
function normalizeText(v=''){return String(v).trim().toLowerCase().replace(/[\s·・_-]+/g,'')}
function moneyNumber(v=''){const n=Number(String(v).replace(/,/g,'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null}
function sizeMatches(actual,expected){const a=normalizeText(actual);if(!a)return false;const options=String(expected||'').split(/[\/、,，;；|]+/).map(normalizeText).filter(Boolean);return a===normalizeText(expected)||options.includes(a)}
function styleMatches(actual,p){const a=normalizeText(actual);return !!a&&(a===normalizeText(p.styleNo)||a===normalizeText(p.name))}
function refreshOrderProducts(){if(!orderProduct)return;const keep=orderProduct.value,items=allOrderProducts();orderProduct.innerHTML='<option value="">请选择商品信息查询编号（SP-xxx）</option>'+items.map(p=>`<option value="${safe(p.id)}">${safe(p.id)} · ${safe(p.brand)} ${safe(p.name)}</option>`).join('');if(items.some(p=>String(p.id)===keep))orderProduct.value=keep}
function expectedMarkup(p){if(!p)return '选中商品信息查询编号后，系统会自动带出商品资料。';return `<b>${safe(p.id)} · ${safe(p.brand)} ${safe(p.name)}</b><span>款号/商品款：${safe(p.styleNo||p.name)}</span><span>颜色：${safe(p.color)}</span><span>尺码：${safe(p.sizes)}</span><span>一口价：${safe(p.price)}</span>`}
function checkRow(ok,label){return `<span class="${ok?'pass':'wait'}">${ok?'✓':'○'} ${label}</span>`}
function evaluateOrder(){const p=currentOrderProduct();expectedProduct.innerHTML=expectedMarkup(p);if(!p){checksEl.innerHTML='';successEl.hidden=true;return}const checks=[
 [!!String(checkCustomer.value||'').trim(),'客户昵称已填写'],
 [normalizeText(checkFields.brand.value)===normalizeText(p.brand),'品牌一致'],
 [styleMatches(checkFields.style.value,p),'款号 / 商品款一致'],
 [normalizeText(checkFields.color.value)===normalizeText(p.color),'颜色一致'],
 [sizeMatches(checkFields.size.value,p.sizes),'尺码一致'],
 [moneyNumber(checkFields.amount.value)!==null&&moneyNumber(checkFields.amount.value)===moneyNumber(p.price),'实收金额等于一口价'],
 [!!receiptState.customer,'客户付款截图已上传'],[!!receiptState.owner,'店主收款截图已上传']];
checksEl.innerHTML=checks.map(x=>checkRow(x[0],x[1])).join('');const done=checks.every(x=>x[0]);successEl.hidden=!done;if(done)completeOrder(p)}
function resetOrderCheck(){orderForm.reset();receiptState.customer='';receiptState.owner='';document.querySelector('#customerReceiptPreview').textContent='客户截图待上传';document.querySelector('#ownerReceiptPreview').textContent='店主截图待上传';expectedProduct.textContent='选中商品信息查询编号后，系统会自动带出商品资料。';checksEl.innerHTML='';successEl.hidden=true}
function completeOrder(p){const records=load(ORDER_KEY),signature=[checkCustomer.value,p.id,checkFields.brand.value,checkFields.style.value,checkFields.color.value,checkFields.size.value,checkFields.amount.value].map(normalizeText).join('|');if(records.some(r=>r.signature===signature))return;const record={id:'ORDER-'+Date.now(),customerNickname:String(checkCustomer.value||'').trim(),productId:p.id,brand:p.brand,name:p.name,styleNo:p.styleNo||'',color:p.color,size:checkFields.size.value,amount:checkFields.amount.value,customerReceipt:receiptState.customer,ownerReceipt:receiptState.owner,signature,completedAt:new Date().toLocaleString('zh-CN',{hour12:false})};if(!save(ORDER_KEY,[record,...records])){successEl.hidden=true;return}upsertCustomerFromOrder(record.customerNickname,record.amount,record.completedAt);const local=load(PRODUCT_KEY),at=local.findIndex(x=>String(x.id)===String(p.id)),q=inventoryNumbers(p);q.sold=Math.min(q.total,q.sold+1);if(q.pending>0)q.pending-=1;q.available=Math.max(0,q.total-q.sold);const sold={...inventoryProduct(p,q),orderState:'下单成功',soldAt:record.completedAt};if(at>=0)local[at]=sold;else local.unshift(sold);save(PRODUCT_KEY,local);renderOrderRecords();renderInventory()}
function shippingMarkup(r){const sent=!!(r.trackingNo&&r.labelImage);return `<div class="shipping-editor" data-order-id="${safe(r.id)}"><div class="shipping-head"><b>发货信息</b><span class="owner-status ${sent?'order-done':'shipping-wait'}">${sent?'✓ 已发货':'待填写'}</span></div><label>物流信息查询编号 *<input data-tracking type="text" maxlength="80" value="${safe(r.trackingNo||'')}" placeholder="手动填写面单上的物流信息查询编号"></label><label>面单照片 *<input data-label-photo type="file" accept="image/jpeg,image/png,image/webp"></label><div class="label-preview" data-label-preview>${r.labelImage?`<img src="${r.labelImage}" alt="面单照片预览">`:'面单照片待上传'}</div><div class="shipping-success" data-shipping-success ${sent?'':'hidden'}>✓ 已发货</div>${r.shippedAt?`<p class="ship-time">发货记录：${safe(r.shippedAt)}</p>`:''}</div>`}
function renderOrderRecords(){if(!recordsEl)return;const items=load(ORDER_KEY);recordsEl.innerHTML=items.length?'<h3 class="records-title">已完成核对与发货</h3>'+items.map(r=>`<article class="owner-item order-record"><div class="record-receipts"><img src="${r.customerReceipt}" alt="客户付款截图"><img src="${r.ownerReceipt}" alt="店主收款截图"></div><div class="record-main"><h3>${safe(r.customerNickname||'未记昵称')} · ${safe(r.productId)} · ${safe(r.brand)} ${safe(r.name)}</h3><p>${safe(r.styleNo||r.name)} · ${safe(r.color)} / ${safe(r.size)} · ¥${safe(r.amount)}</p><span class="owner-status order-done">✓ 下单成功</span><p>${safe(r.completedAt)}</p>${shippingMarkup(r)}</div></article>`).join(''):'<div class="empty-owner">还没有自动核对成功的订单</div>'}
function publishShipping(record){const products=load(PRODUCT_KEY),all=allOrderProducts(),p=all.find(x=>String(x.id)===String(record.productId));if(!p)return;const at=products.findIndex(x=>String(x.id)===String(record.productId)),shipped=inventoryProduct({...p,orderState:'下单成功',shippingState:'已发货',trackingNo:record.trackingNo,shippedAt:record.shippedAt});if(at>=0)products[at]=shipped;else products.unshift(shipped);save(PRODUCT_KEY,products)}
function finishShipping(orderId){const records=load(ORDER_KEY),at=records.findIndex(r=>String(r.id)===String(orderId));if(at<0)return;const r=records[at];if(!r.trackingNo||!r.labelImage)return;if(!r.shippedAt)r.shippedAt=new Date().toLocaleString('zh-CN',{hour12:false});records[at]=r;if(save(ORDER_KEY,records))publishShipping(r)}
orderProduct.addEventListener('change',()=>{receiptState.customer='';receiptState.owner='';document.querySelector('#customerReceipt').value='';document.querySelector('#ownerReceipt').value='';document.querySelector('#customerReceiptPreview').textContent='客户截图待上传';document.querySelector('#ownerReceiptPreview').textContent='店主截图待上传';Object.values(checkFields).forEach(x=>x.value='');evaluateOrder()});
checkCustomer.addEventListener('input',evaluateOrder);Object.values(checkFields).forEach(x=>x.addEventListener('input',evaluateOrder));orderForm.addEventListener('submit',e=>e.preventDefault());
async function prepareReceipt(input,key,previewId){const file=input.files[0];if(!file){receiptState[key]='';evaluateOrder();return}const target=document.querySelector('#'+previewId);target.textContent='正在处理…';try{receiptState[key]=await compress(file,700,.55);target.innerHTML=`<img src="${receiptState[key]}" alt="截图预览">`;evaluateOrder()}catch(e){receiptState[key]='';input.value='';target.textContent=e.message||'截图无法读取';evaluateOrder()}}
document.querySelector('#customerReceipt').addEventListener('change',e=>prepareReceipt(e.currentTarget,'customer','customerReceiptPreview'));document.querySelector('#ownerReceipt').addEventListener('change',e=>prepareReceipt(e.currentTarget,'owner','ownerReceiptPreview'));
recordsEl.addEventListener('change',e=>{const input=e.target.closest('[data-tracking]');if(!input)return;const panel=input.closest('[data-order-id]'),records=load(ORDER_KEY),at=records.findIndex(r=>String(r.id)===String(panel.dataset.orderId));if(at<0)return;records[at].trackingNo=input.value.trim();save(ORDER_KEY,records);if(records[at].trackingNo&&records[at].labelImage){finishShipping(records[at].id);panel.querySelector('[data-shipping-success]').hidden=false;panel.querySelector('.owner-status').textContent='✓ 已发货';panel.querySelector('.owner-status').classList.remove('shipping-wait');panel.querySelector('.owner-status').classList.add('order-done')}});
recordsEl.addEventListener('change',async e=>{const input=e.target.closest('[data-label-photo]');if(!input)return;const file=input.files[0],panel=input.closest('[data-order-id]'),target=panel.querySelector('[data-label-preview]');if(!file)return;target.textContent='正在处理…';try{const image=await compress(file,900,.62),records=load(ORDER_KEY),at=records.findIndex(r=>String(r.id)===String(panel.dataset.orderId));if(at<0)return;records[at].labelImage=image;if(!save(ORDER_KEY,records))return;target.innerHTML=`<img src="${image}" alt="面单照片预览">`;if(records[at].trackingNo){finishShipping(records[at].id);renderOrderRecords();refresh()}}catch(err){input.value='';target.textContent=err.message||'面单照片无法读取'}});
document.querySelector('#clearOrders').addEventListener('click',()=>{if(confirm('确认清空这台设备里的核对记录、付款截图和面单照片吗？商品状态不会自动恢复。')){localStorage.removeItem(ORDER_KEY);resetOrderCheck();renderOrderRecords()}});
