/* 薯片小铁美国代购原创网站模板｜创作者：薯片小铁（Aria）｜© 2026，使用规则见版权与使用说明.txt */
const FIXED_PIN='9611',PRODUCT_KEY='ownerProducts',ORDER_KEY='ownerOrderChecks',CUSTOMER_KEY='ownerCustomers',BRAND_KEY='ownerBrands';
const DEFAULT_BRANDS=[{name:'Lululemon',color:'#e31937',kind:'lululemon'},{name:'Polo',color:'#ef9fbd',kind:'polo'},{name:'Adidas',color:'#123b70',kind:'adidas'},{name:'Nike',color:'#f36c21',kind:'nike'},{name:'The North Face',color:'#111111',kind:'north'},{name:'Other Brands',color:'#c2185b',kind:'other'}];
const gate=document.querySelector('#pinGate'),dash=document.querySelector('#dashboard'),pin=document.querySelector('#pinInput'),pinStatus=document.querySelector('#pinStatus');
function unlock(){gate.hidden=true;dash.hidden=false;sessionStorage.setItem('ownerUnlocked','1');refresh()}
document.querySelector('#pinForm').addEventListener('submit',e=>{e.preventDefault();if(pin.value===FIXED_PIN)unlock();else{pinStatus.textContent='密码不正确，请重新输入。';pin.select()}});
document.querySelector('#lockButton').addEventListener('click',()=>{sessionStorage.removeItem('ownerUnlocked');dash.hidden=true;gate.hidden=false;pin.value='';pinStatus.textContent='已锁定。';pin.focus()});
const form=document.querySelector('#productForm'),list=document.querySelector('#ownerProducts'),wishesEl=document.querySelector('#wishRecords'),fileInput=document.querySelector('#imageFile'),preview=document.querySelector('#imagePreview'),imageStatus=document.querySelector('#imageStatus');
function load(key){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}function save(key,items){try{localStorage.setItem(key,JSON.stringify(items));return true}catch{alert('手机本地空间不足。请先导出文件，再删除部分本机图片或改用更小的照片。');return false}}
const safe=(v='')=>{const n=document.createElement('span');n.textContent=String(v);return n.innerHTML};
function validBrands(items){return Array.isArray(items)?items.filter(b=>b&&String(b.name||'').trim()).map(b=>({name:String(b.name).trim(),color:/^#[0-9a-f]{6}$/i.test(b.color||'')?b.color:'#d95f84',kind:String(b.kind||'custom')})):[]}
function getBrands(){const local=validBrands(load(BRAND_KEY));if(local.length)return local;const published=validBrands(window.BRANDS);return published.length?published:DEFAULT_BRANDS}
const brandForm=document.querySelector('#brandForm'),brandRecords=document.querySelector('#brandRecords'),brandName=document.querySelector('#brandName'),brandColor=document.querySelector('#brandColor'),brandColorValue=document.querySelector('#brandColorValue'),brandStatus=document.querySelector('#brandStatus'),productBrand=document.querySelector('#productBrand');
function renderBrandManager(){const brands=getBrands(),keep=productBrand.value;productBrand.innerHTML='<option value="">请选择</option>'+brands.map(b=>`<option value="${safe(b.name)}">${safe(b.name)}</option>`).join('');if(brands.some(b=>b.name===keep))productBrand.value=keep;brandRecords.innerHTML=brands.map((b,i)=>`<article class="brand-record"><span class="brand-swatch" style="--swatch:${safe(b.color)}"></span><div><b>${safe(b.name)}</b><small>${safe(b.color.toUpperCase())}</small></div><label class="brand-color-edit" title="修改品牌颜色"><span>改颜色</span><input type="color" value="${safe(b.color)}" data-brand-color="${i}"></label>${b.name==='Other Brands'?'<span class="protected-brand">默认分类</span>':`<button class="delete-item" type="button" data-brand-delete="${i}">删除</button>`}</article>`).join('')}
brandColor.addEventListener('input',()=>brandColorValue.value=brandColor.value.toUpperCase());
brandForm.addEventListener('submit',e=>{e.preventDefault();const name=brandName.value.trim().replace(/\s+/g,' '),brands=getBrands();if(!name)return;if(brands.some(b=>b.name.toLocaleLowerCase()===name.toLocaleLowerCase())){brandStatus.textContent='这个品牌已经存在，可以直接在列表里修改颜色。';return}brands.splice(Math.max(0,brands.length-1),0,{name,color:brandColor.value,kind:'custom'});if(save(BRAND_KEY,brands)){brandForm.reset();brandColor.value='#d95f84';brandColorValue.value='#D95F84';brandStatus.textContent=`已添加 ${name}。重新导出 products.js 后会发布给所有客户。`;renderBrandManager()}});
brandRecords.addEventListener('change',e=>{const input=e.target.closest('[data-brand-color]');if(!input)return;const brands=getBrands(),b=brands[Number(input.dataset.brandColor)];if(!b)return;b.color=input.value;if(save(BRAND_KEY,brands)){brandStatus.textContent=`已更新 ${b.name} 的品牌色。`;renderBrandManager()}});
brandRecords.addEventListener('click',e=>{const button=e.target.closest('[data-brand-delete]');if(!button)return;const brands=getBrands(),removed=brands[Number(button.dataset.brandDelete)];if(!removed||!confirm(`删除品牌“${removed.name}”吗？这个品牌的商品会自动归入 Other Brands。`))return;const next=brands.filter((_,i)=>i!==Number(button.dataset.brandDelete)),all=ownerAllProducts(),local=load(PRODUCT_KEY),affected=all.filter(p=>String(p.brand).toLocaleLowerCase()===removed.name.toLocaleLowerCase()).map(p=>({...p,brand:'Other Brands'}));affected.forEach(p=>{const at=local.findIndex(x=>String(x.id)===String(p.id));if(at>=0)local[at]=p;else local.unshift(p)});if(save(BRAND_KEY,next)&&save(PRODUCT_KEY,local)){brandStatus.textContent=`已删除 ${removed.name}，${affected.length} 件商品已归入 Other Brands。`;renderBrandManager();refresh()}});
function getImages(p){if(Array.isArray(p.images))return p.images.filter(Boolean);return p.image?[p.image]:[]}
function cleanProduct(p={}){const {store,storeName,storeLocation,location,deadline,note,...rest}=p;return rest}
function showPreview(images=[],target=preview){target.innerHTML=images.length?images.map((src,i)=>`<img src="${src}" alt="图片预览 ${i+1}">`).join(''):'建议依次选择：整体、吊牌价签、细节'}
function ownerAllProducts(){const base=(Array.isArray(window.PRODUCTS)?window.PRODUCTS:[]).map(cleanProduct),local=load(PRODUCT_KEY).map(cleanProduct);return [...base.filter(p=>!local.some(x=>String(x.id)===String(p.id))),...local]}
function inventoryNumbers(p){const fromStock=Number((String(p.stock||'').match(/\d+/)||[])[0]),total=Math.max(1,Math.floor(Number(p.totalQty)||fromStock||1));let sold=Math.max(0,Math.floor(Number(p.soldQty)||0));if(!('soldQty' in p)&&(p.status==='已售出'||p.status==='已售罄'||p.orderState==='下单成功'))sold=total;sold=Math.min(total,sold);const pending=Math.max(0,Math.floor(Number(p.pendingQty)||0));return{total,sold,pending,available:Math.max(0,total-sold)}}
function inventoryStatus(p){const q=inventoryNumbers(p);if(q.available===0)return'已售罄';if(q.available===1)return'库存紧张';return'可购买'}
function inventoryText(p){const q=inventoryNumbers(p);return`剩余 ${q.available} 件（共 ${q.total} 件）`}
function inventoryProduct(p,q=inventoryNumbers(p)){return{...p,totalQty:q.total,soldQty:q.sold,pendingQty:q.pending,stock:`剩余 ${q.available} 件`,status:q.available===0?'已售罄':q.available===1?'库存紧张':'可购买',updated:new Date().toLocaleString('zh-CN',{hour12:false})}}
function renderInventory(){const board=document.querySelector('#inventoryBoard');if(!board)return;const items=ownerAllProducts();board.innerHTML=items.length?items.map(p=>{const q=inventoryNumbers(p);return`<article class="inventory-item" data-product-id="${safe(p.id)}"><div class="inventory-title"><div><h3>${safe(p.id)} · ${safe(p.brand)} ${safe(p.name)}</h3><p>${safe(p.color)} / ${safe(p.sizes)}</p></div><span class="inventory-available ${q.available===0?'zero':''}">剩余 ${q.available}</span></div><div class="inventory-counts"><span>总数 <b>${q.total}</b></span><span>待确认 <b>${q.pending}</b></span><span>已售 <b>${q.sold}</b></span></div><div class="inventory-actions"><button type="button" data-inventory-action="pending-add">登记待确认</button><button type="button" data-inventory-action="pending-cancel" ${q.pending===0?'disabled':''}>取消待确认</button><button class="confirm-sale" type="button" data-inventory-action="sold-add" ${q.available===0?'disabled':''}>确认售出 −1</button><button type="button" data-inventory-action="sold-remove" ${q.sold===0?'disabled':''}>撤销售出 +1</button></div></article>`}).join(''):'<div class="empty-owner">发布商品后，可在这里统一确认待定、售出或取消。</div>'}
function cleanWishes(){const wishes=load('wishList').map(entry=>{const {notes,remark,wechat,wechatId,wechatNumber,consent,...rest}=entry||{};return rest});try{localStorage.setItem('wishList',JSON.stringify(wishes))}catch{}return wishes}
function refresh(){const items=load(PRODUCT_KEY),wishes=cleanWishes(),wanted=load('wantedProducts'),customers=load(CUSTOMER_KEY);document.querySelector('#statProducts').textContent=items.length;document.querySelector('#statCustomers').textContent=customers.length;document.querySelector('#statWishes').textContent=wishes.length;document.querySelector('#statWanted').textContent=wanted.length;list.innerHTML=items.length?items.map((p,i)=>`<article class="owner-item">${getImages(p)[0]?`<img class="owner-thumb" src="${getImages(p)[0]}" alt="">`:''}<div><h3>${safe(p.brand)} · ${safe(p.name)}</h3><p>${safe(p.styleNo||'无款号')} · ${safe(p.color)} / ${safe(p.sizes)}</p><p>${safe(p.price)} · ${safe(inventoryText(p))}</p><span class="owner-status ${inventoryNumbers(p).available===0?'order-done':''}">${safe(inventoryStatus(p))}</span></div><div class="item-actions"><button class="edit-item" data-edit="${i}">编辑</button><button class="delete-item" data-delete="${i}">删除</button></div></article>`).join(''):'<div class="empty-owner">还没有在本机添加商品</div>';renderWishes(wishes);renderInventory();refreshOrderProducts();renderOrderRecords();renderCustomers();renderBrandManager()}
function renderWishes(items){wishesEl.innerHTML=items.length?items.slice().reverse().map(w=>`<article class="owner-item"><div><h3>${safe(w.item)}</h3><p>${safe(w.color||'未指定')} / ${safe(w.size||'未指定')}</p></div></article>`).join(''):'<div class="empty-owner">这台设备还没有愿望记录</div>'}
async function compress(file,max=1100,quality=.72){if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error('请使用 JPG、PNG 或 WebP 图片。');const url=URL.createObjectURL(file);try{const img=await new Promise((ok,bad)=>{const x=new Image();x.onload=()=>ok(x);x.onerror=bad;x.src=url});const scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',quality)}finally{URL.revokeObjectURL(url)}}
fileInput.addEventListener('change',async()=>{const files=[...fileInput.files].slice(0,3);if(!files.length)return;if(fileInput.files.length>3)imageStatus.textContent='最多使用前 3 张，正在压缩…';else imageStatus.textContent='正在压缩照片…';try{const images=[];for(const f of files)images.push(await compress(f));form.elements.images.value=JSON.stringify(images);showPreview(images);imageStatus.textContent=`已准备 ${images.length} 张照片。第一张会作为主图。`}catch(e){imageStatus.textContent=e.message||'图片无法读取，请换一张。';fileInput.value=''}});
form.addEventListener('submit',e=>{e.preventDefault();let images=[];try{images=JSON.parse(form.elements.images.value||'[]')}catch{}if(!images.length){imageStatus.textContent='请至少选择一张现场照片。';fileInput.focus();return}const data=Object.fromEntries(new FormData(form).entries()),items=load(PRODUCT_KEY).map(cleanProduct);delete data.imageFile;data.images=images;data.image=images[0];const id=data.id||'SP-'+Date.now().toString().slice(-8),at=items.findIndex(x=>String(x.id)===String(id)),previous=at>=0?items[at]:null,totalQty=Math.max(1,Math.floor(Number(data.totalQty)||1)),old=previous?inventoryNumbers(previous):{sold:0,pending:0};data.totalQty=totalQty;data.soldQty=Math.min(totalQty,old.sold);data.pendingQty=old.pending;const item=inventoryProduct({...data,id,updated:new Date().toLocaleString('zh-CN',{hour12:false})});if(at>=0)items[at]=item;else items.unshift(item);if(!save(PRODUCT_KEY,items))return;resetForm();refresh();alert('已保存到本机并按品牌归类。确认无误后导出 products.js，上传 GitHub 才会发布给客户。')});
function resetForm(){form.reset();form.elements.id.value='';form.elements.images.value='';fileInput.required=true;showPreview([]);imageStatus.textContent='照片会在手机里压缩并嵌入导出文件；最多 3 张，第一张作为主图。';document.querySelector('#cancelEdit').hidden=true}
list.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),items=load(PRODUCT_KEY);if(edit){const p=items[Number(edit.dataset.edit)];Object.entries(p).forEach(([k,v])=>{if(form.elements[k]&&k!=='images')form.elements[k].value=v||''});if(form.elements.totalQty)form.elements.totalQty.value=inventoryNumbers(p).total;form.elements.images.value=JSON.stringify(getImages(p));fileInput.required=false;showPreview(getImages(p));imageStatus.textContent='正在编辑已有照片；如需更换，请重新选择（最多 3 张）。';document.querySelector('#cancelEdit').hidden=false;form.scrollIntoView({behavior:'smooth'})}if(del&&confirm('确认删除这条本机商品吗？')){items.splice(Number(del.dataset.delete),1);if(save(PRODUCT_KEY,items))refresh()}});
document.querySelector('#cancelEdit').addEventListener('click',resetForm);
const inventoryBoard=document.querySelector('#inventoryBoard');
inventoryBoard.addEventListener('click',e=>{const button=e.target.closest('[data-inventory-action]');if(!button)return;const card=button.closest('[data-product-id]'),id=card&&card.dataset.productId,p=ownerAllProducts().find(x=>String(x.id)===String(id));if(!p)return;const q=inventoryNumbers(p),action=button.dataset.inventoryAction;if(action==='pending-add')q.pending+=1;if(action==='pending-cancel')q.pending=Math.max(0,q.pending-1);if(action==='sold-add'){if(q.available===0)return alert('没有剩余库存，不能继续确认售出。');q.sold+=1;if(q.pending>0)q.pending-=1}if(action==='sold-remove'){q.sold=Math.max(0,q.sold-1)}q.available=Math.max(0,q.total-q.sold);const local=load(PRODUCT_KEY),at=local.findIndex(x=>String(x.id)===String(id)),updated=inventoryProduct(p,q);if(at>=0)local[at]=updated;else local.unshift(updated);if(save(PRODUCT_KEY,local))refresh()});
function downloadJS(name,comment,varName,items){const content=`/* ${comment} */\nwindow.${varName} = ${JSON.stringify(items,null,2)};\n`,blob=new Blob([content],{type:'text/javascript;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.querySelector('#exportButton').addEventListener('click',()=>{const base=(Array.isArray(window.PRODUCTS)?window.PRODUCTS:[]).map(cleanProduct),local=load(PRODUCT_KEY).map(cleanProduct),all=[...base.filter(p=>!local.some(x=>x.id===p.id)),...local].map(cleanProduct),brands=getBrands(),content=`/* 店主工作台导出：包含品牌设置和商品；发布前请再次核实照片、价格、尺码和库存。 */\nwindow.BRANDS = ${JSON.stringify(brands,null,2)};\nwindow.PRODUCTS = ${JSON.stringify(all,null,2)};\n`,blob=new Blob([content],{type:'text/javascript;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='products.js';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
document.querySelector('#clearWishes').addEventListener('click',()=>{if(confirm('只清空这台设备里的愿望记录，确认继续吗？')){localStorage.removeItem('wishList');refresh()}});


showForm.addEventListener('submit',e=>{e.preventDefault();if(!showForm.elements.image.value)return alert('请先选择一张照片。');const d=Object.fromEntries(new FormData(showForm).entries()),items=load(SHOW_KEY);items.unshift({...d,id:'show-'+Date.now()});if(save(SHOW_KEY,items)){showForm.reset();showForm.elements.image.value='';showPreviewEl.textContent='选择已获得客户同意的照片';refresh()}});


customerRecords.addEventListener('click',e=>{const edit=e.target.closest('[data-customer-edit]'),del=e.target.closest('[data-customer-delete]');if(edit){const c=customerById(edit.dataset.customerEdit);if(!c)return;customerForm.elements.id.value=c.id;customerForm.elements.nickname.value=c.nickname||'';customerForm.elements.tags.value=c.tags||'';customerForm.elements.note.value=c.note||'';document.querySelector('#cancelCustomerEdit').hidden=false;customerForm.scrollIntoView({behavior:'smooth',block:'center'})}if(del&&confirm('确认删除这份客户档案吗？只删除档案，不会删除订单或改变库存。')){const items=load(CUSTOMER_KEY).filter(c=>String(c.id)!==String(del.dataset.customerDelete));if(save(CUSTOMER_KEY,items))refresh()}});
document.querySelector('#cancelCustomerEdit').addEventListener('click',resetCustomerForm);customerSearch.addEventListener('input',renderCustomers);

if(sessionStorage.getItem('ownerUnlocked')==='1')unlock();
